[client]
# Убирает лишние пункты меню, оставляя интерфейс чистым
toolbarMode = "minimal"

[[theme.fontFaces]]
family="pt-astra-sans-bold-italic"
url="pt-astra-sans-bold-italic.woff"
style = 'italic'

[theme]
base="light"
borderColor="#4F46E5"
font = "pt-astra-sans-bold-italic"

[theme.sidebar]
backgroundColor="#F8FAFC"
secondaryBackgroundColor="#E0E7FF"

[ui]
# Полностью скрывает верхнюю панель управления
hideTopBar = true

