[client]
# Убирает лишние пункты меню, оставляя интерфейс чистым
toolbarMode = "minimal"

[[theme.fontFaces]]
family="pt-astra-sans-bold-italic"
url="pt-astra-sans-bold-italic.woff"
style = 'italic'

[theme]
base="dark"
borderColor="#334155"
font = "pt-astra-sans-bold-italic"
backgroundColor="#660082"

[theme.sidebar]
backgroundColor="#0F172A"
secondaryBackgroundColor="#1E293B"

[ui]
# Полностью скрывает верхнюю панель управления
hideTopBar = true








